config/routes.rb
Rails.application.routes.draw do
  resources :accounts, only: [:show, :new, :create] do
    resources :transactions, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  validates :address, uniqueness: true
  has_many :transactions

  TRANSACTION_TYPES = ['deposito', 'retiro']
  LabelValue = Struct.new(:label, :value)
  TRANSACTION_TYPES_SELECT = TRANSACTION_TYPES.collect do |transaction|
    LabelValue.new(transaction, transaction)
  end

  def to_param
    address
  end

  def self.find(input)
    find_by_address(input)
  end

  def sha_address(string)
    Digest::SHA256.hexdigest(string)
  end

  def verify(transaction_params)
    verify_password(transaction_params[:password]) &&
    verify_instruction(transaction_params[:instruction], transaction_params[:amount])
  end

  def verify_password(password)
    address == sha_address(password)
  end

  def verify_instruction(instruction, amount)
    if instruction == 'retiro'
      (balance - amount.to_i) >= 0
    elsif instruction == 'deposito'
      true
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account

  after_create :apply_transaction

  def apply_transaction
    balance = get_new_balance
    account.update(balance: balance)
  end

  def get_new_balance
    case instruction
    when 'deposito'
      account.balance + amount
    when 'retiro'
      account.balance - amount
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show]

  def new
    @account = Account.new
  end

  def show
  end

  def create
    password = account_params[:password]
    final_params = account_params.except(:password).merge(address: Account.new.sha_address(password))
    @account = Account.new(final_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    def set_account
      @account = Account.includes(:transactions).find_by_address(params[:id])
      redirect_to new_account_path unless @account
    end

    def account_params
      params.require(:account).permit(:address, :balance, :password)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_account

  def create
    @transaction = @account.transactions.new(transaction_params.except(:password))

    respond_to do |format|
      if @account.verify(transaction_params) && @transaction.save
        format.html { redirect_to @account, notice: 'Transaction was successfully created.' }
      else
        format.html { redirect_to @account, notice: 'Transaction failed' }
      end
    end
  end

  private
    def set_account
      @account = Account.find(params[:account_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:account_id, :description, :amount, :instruction, :password)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :account_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/_transaction_form.html.erb
<%= form_with(url: account_transactions_path(@account), model: Transaction.new, local: true) do |form| %>
  <div class="field">
    <%= form.label :password %>
    <%= form.text_area :password, id: :transaction_password %>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :transaction_description %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, id: :transaction_amount %>
  </div>

  <div class="field">
    <%= form.label :instruction %>
    <%= form.collection_select :instruction, Account::TRANSACTION_TYPES_SELECT, :label, :value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.address %></td>
        <td><%= account.balance %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @account.address %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @account.balance %>
</p>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Amount</th>
      <th>Instruction</th>
    </tr>
  </thead>

  <tbody>
    <% @account.transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.description %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.instruction %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'transaction_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BananaCoin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.number_field :account_id, id: :transaction_account_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :transaction_description %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, id: :transaction_amount %>
  </div>

  <div class="field">
    <%= form.label :instruction %>
    <%= form.text_field :instruction, id: :transaction_instruction %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Instruction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.account_id %></td>
        <td><%= transaction.description %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.instruction %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @transaction.account_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Instruction:</strong>
  <%= @transaction.instruction %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>